### ISSUE TITLE
Confirm atomic wallet calls, not whole transaction

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#106]
Audit issue 4. "A single operation causes all other operations in an execution cycle to fail"
"Should one of these calls fail, the whole transaction reverts"

Show this is not the case with a unit test.

**Comment by voltrevo** [comment]
There's some terminology mixup going on here. To clarify, inside the project we use the terms like this:
- A bundle contains a list of operations
- An operation contains a list of actions

Given the above, the following features are intended:
- A failing operation _does not_ fail the other operations of the bundle
- A failing action _does_ fail the other actions of the operation

As discussed, tests will be added for the two features above.
