### ISSUE TITLE
5. Verification gateway could accidentally be set to non-conformant contract

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#107]
The function _setTrustedBLSGateway in VerificationGateway.sol allows a wallet
user to migrate to a new verification gateway. The function checks that the address supplied
as a parameter is a smart contract rather than an externally owned account, but does not
verify that the contract supports the required interface. This may lead to accidentally
migrating to a smart contract that does not support verification gateway functionality.
Recommendation
Consider implementing interface (https://eips.ethereum.org/EIPS/eip-165). detection, for example EIP-165

**Comment by voltrevo** [comment]
As discussed, we're going to add `isVerificationGateway -> true` to the verification gateway and use this instead.
- Easier
- Don't need or want to actually constrain the interface of VerificationGateway
