### ISSUE TITLE
Add HD wallet support

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#131]
### Background

https://wiki.trezor.io/Hierarchical_deterministic_wallet

### Current Behavior

In the extension, we currently generate private keys by generating a random hex: https://github.com/jzaki/bls-wallet/blob/main/extension/source/App.ts#L151-L153

This is also how we generate private keys with new incoming updates: https://github.com/jzaki/bls-wallet/pull/42/files#diff-7ae0a811d81712d110aacca5950b30f483297c0182f6aba6ec817dc3b6ea312eR36-R39

### New Behavior

Have private keys generated using the HD wallet specs.

- `ether.js` provides utlity classes and functions to do this: https://docs.ethers.io/v5/api/utils/hdnode/
- [eth-hd-keyring](https://github.com/MetaMask/eth-hd-keyring) is a MetaMask compatible implementation which could work nicely with extension dApp interaction updates.

### Issues

[EIP-2333](https://eips.ethereum.org/EIPS/eip-2333) (stagnant, not finalized)

From `Deficiencies of the existing mechanism `:
```
The curve BLS12-381 used for BLS signatures within Ethereum 2.0 (alongside many other projects) mandates a new key derivation scheme. The most commonly used scheme for key derivation within Ethereum 1.x is BIP32 (also known as HD derivation) which deems keys greater than the curve order invalid. Based on the order of the private key subgroup of BLS12-381 and the size of the entropy utilised, more than 54% of keys generated by BIP32 would be invalid. (secp256k1 keys derived by BIP32 are invalid with probability less than 1 in 2-127.)
```

We currently/will get around this by [hashing the private key value versus directly setting it](https://github.com/thehubbleproject/hubble-bls/pull/28#discussion_r794143913), but it would be great if we could generate an HD wallet whose derived keys work natively for BLS operations.

**Comment by kautukkundan** [comment]
@jacque006 why was this reopened? Was it because of the inconsistent mapping as described in [EIP-2333](https://eips.ethereum.org/EIPS/eip-2333)?

If yes, how about we close this issue and create a new one to track specifically the new spec as this issue is strictly about adding HD Wallet generation which was already merged.

**Comment by jacque006** [comment]
Not sure why I reopened this, closing.
