### ISSUE TITLE
Lock Wallet Attack

### ISSUE THREAD

**Issue by kcharbo3** [jzaki/bls-wallet#141]
During wallet recovery, this line may cause problems without proper checks: https://github.com/jzaki/bls-wallet/blob/main/contracts/contracts/VerificationGateway.sol#L197

There's no restriction that the user recovering their wallet knows the private keys to the newBLSKey. They can recover their wallet to any public key they want. This will set externalWalletsFromHash[any public key] to their wallet address. This would lock up any pre-existing wallet with those public keys since that wallet's connection in the VerificationGateway is gone.

Here is how an attack would occur: 
1. Attacker sees a wallet they want to lock. Call it wallet A
2. Attacker creates new wallet
3. Attacker sets their wallet’s recoveryHash
4. After a week attacker calls setAnyPending() to ensure their recoveryHash is set
5. Attacker calls recoverWallet(their new wallet key hash, salt, the PubKey of wallet A)
6. This sets externalWalletsFromHash[wallet A pub key hash] to the attackers wallet
7. The link between wallet A and the VG is now gone
8. The wallet is locked because only the VG can call performOperation. The user can’t reset their wallet using setExternalWallet either since the caller of that function must be the wallet itself
9. The wallet has effectively been locked

**Comment by jacque006** [comment]
Resolved in https://github.com/jzaki/bls-wallet/pull/150
