### ISSUE TITLE
Bundle aggregation diagram

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#157]
- [x] Put something together that James can use
- ~Make use of diagram(s) in docs~

**Comment by voltrevo** [comment]
I've put together a few different things you might find useful:
https://drive.google.com/drive/folders/175ja-C6zmlGsj3OXcOIh50Xwj5wMnivf?usp=sharing
![Screen Shot 2022-03-22 at 5 18 05 pm](https://user-images.githubusercontent.com/9291586/159419731-3f0426bb-92ff-4531-91fd-b5a44a27b032.png)
![Screen Shot 2022-03-22 at 5 18 13 pm](https://user-images.githubusercontent.com/9291586/159419743-b6bc3b56-2fa8-4520-8199-f8e8d2b6c25e.png)
![Screen Shot 2022-03-22 at 5 18 27 pm](https://user-images.githubusercontent.com/9291586/159419752-02b38873-5bab-479e-bed4-115fe346bf0d.png)
![Screen Shot 2022-03-22 at 5 18 37 pm](https://user-images.githubusercontent.com/9291586/159419762-0d711fae-05c4-474a-a3f0-c547818b03ab.png)

**Comment by jacque006** [comment]
@voltrevo These are great, where do you think would be the best place to put them? I could see them top level or in a docs dir (such as the one in https://github.com/jzaki/bls-wallet/pull/158)

**Comment by voltrevo** [comment]
@jacque006 Cheers. They're a bit rough in their current form. James is gonna make use of them in a couple of places (blog/article). If we want to preserve these somewhere I suggest we evaluate after James has a chance to iterate on them. In the meantime they're here and have the google drive link.

**Comment by voltrevo** [comment]
Decided to re-open this so that we can also track making use of the diagrams in our docs.
