### ISSUE TITLE
Create example dapp that uses bls-wallet and pays user txs

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#170]
DApps can pre-pay user txs
eg 100txs/month paid

Flow:
User registers their wallet with a dapp
- User signs transactions proposed by dapp
  - dapp contract call
  - dapp wallet transfers token to tx.origin
DApp aggregates signed txs and submits to Verification Gateway contract

[Related](https://hackmd.io/1Z4qUZODScqMlNIBucugOg#Future-Dapp-adds-reward-action-to-operation)

**Comment by voltrevo** [comment]
> dapp wallet transfers token to tx.origin
> DApp aggregates signed txs and submits to Verification Gateway contract

These points are contradictory since if the dApp is submitting directly to the gateway there's no need to pay tx.origin.

I'm assuming you meant that the dApp submits to an aggregator.
