### ISSUE TITLE
Store confirmed/historical bundles in db

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#190]
Currently, confirmed/submitted bundles are not persisted in the aggregator. We should add a db table or column for status which tracks them so they can be looked up in the future, or be available between aggregator restarts.

**Comment by nooma-42** [comment]
This issue seems to solve? In aggregator/src/app/app.ts, `sqlite.DB(env.DB_PATH)` is given a db path, which create the db file as [doc of deno sqlite](https://deno.land/x/sqlite@v3.7.0/mod.ts?s=DB) suggests.
```
const bundleTable = new BundleTable(
    new sqlite.DB(env.DB_PATH), //  The file at the given path will be opened with the mode specified in options.
    (sql, params) => {
      if (env.LOG_QUERIES) {
        emit({
          type: "db-query",
          data: { sql, params },
        });
      }
    },
  );
```

**Comment by jacque006** [comment]
@NOOMA-42 Good catch. We do store a number of details in SQL DB, but I'm not sure if we persist everything we need ATM.

@blakecduncan @voltrevo Has previous work in this area take care of this issue?

**Comment by blakecduncan** [comment]
> 

@NOOMA-42  Thanks for flagging.  Yes, I believe we can close this issue as we no longer delete bundles from the DB.
