### ISSUE TITLE
Load submitted onchain bundles into db on aggregator startup

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#191]
When the aggregator starts up, it should scan through the current chain it is pointing at to retrieve and store any historical bundles that have been submitted so clients can look them up if need be.
- Add a process on aggregator startup which scan the chain in a block range for bundles.
- Track the block number the aggregator has scanned up (checkpoint) so it does not have to scan the entire chain history on every startup.

**Comment by voltrevo** [comment]
Hmm, I see this as out-of-scope.

This is more the domain of a block explorer. At scale, storing the whole history of BLS Wallet transactions is a big ask and I think an unnecessary barrier to entry for running an aggregator.

Would like to see a separate tool for this though. Wdyt?

**Comment by jacque006** [comment]
I think having a way for block explorers to parse BLS Wallet/EIP-4437 transactions is good future thing to have, and definitely out of scope of agg hardening. 

The problem with not implementing this is that it will create issues if someone is running multiple agg instances, or if a user queries for a bundle from an agg that is on the same network but that they didn't submit to. I can see the mutli agg scenario being common in production settings where you want to run 2 more or more instances to allow for zero downtime updates via a [blue/green deploys](https://www.redhat.com/en/topics/devops/what-is-blue-green-deployment), want redundancy in case of a crash/panic, or want to scale agg instances to deal with higher traffic/server loads.

There will also be problems when looking up receipts if those instances are behind a load balancer. When it splits/round robins traffic between instances, it will find a receipt when it hits the instance it was submitted to but will fail/404 when it hits another instance. (This would not be true if they are attached to the same pg db/table)

We also are going to have the issue that if someone submits a bundle to two aggregators (because they really, really want it to go through fast), they will get two different bundle hashes back unless we implement https://github.com/web3well/bls-wallet/issues/192

I also realized we probably don't want to do this just on startup, but on every block to keep the agg in sync with current chain state.
