### ISSUE TITLE
Use of client module via MetaMask Snap for a dapp on Arbitrum testnet

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#197]
Implement bls-client functionality in a [metamask snap](https://docs.metamask.io/guide/snaps-development-guide.html) (NB: "only available in MetaMask Flask", ie Chrome desktop only)

- receive regular transactions from an Arbitrum dapp (testnet first)
- show the tx details to the user
- with user confirmation, sign an operation containing the transaction (action)
- submit signed operation to aggregation server
- communicate completion to user and/or dapp

**Comment by kautukkundan** [comment]
Keeping it on hold as suggested by @jzaki. Will revisit later.
