### ISSUE TITLE
Incomplete: Simulate tx (callStatic) then check agg balance

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#2]
Currently checks sender has balance before submitting batch.
Instead:
- dummy block, apply tx, check agg balance
  - ppl send reward amount with tx, check with balance at end

Should handle dApp or other paying reward token to aggregator.

**Comment by jzaki** [comment]
Related test -> https://github.com/jzaki/bls-wallet/blob/main/contracts/test/walletAction-test.ts#L261

**Comment by voltrevo** [comment]
Superseded by #133.
