### ISSUE TITLE
Implement EIP-1271 (Signature Validation)

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#201]
### Problem

Currently, it is difficult for a dApp to verify BLS signed messages done by our client library/extension. They must implement custom logic.

### Possible Solution

[EIP-1271](https://eips.ethereum.org/EIPS/eip-1271) provides a common interface that allows a contract to validate a signature. We could implement it by:
- Add new validate signature function to `VerificationGateway.sol` that can verify a BLS signed message.
- Implement `ERC1271` spec on `BLSWallet.sol`, using the new signature validation function above.

This creates tight coupling between the wallet and gateway, which could be undesirable.

**Comment by jzaki** [comment]
Related -> https://ethereum-magicians.org/t/erc-4337-account-abstraction-via-entry-point-contract-specification/7160/68

**Comment by JohnGuilding** [comment]
Completed in #561
