### ISSUE TITLE
Bug: text field borders increase the size of the text fields, causing the rest of the page to move

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#213]
Video demo/explanation:
https://youtu.be/VI065g8rO1Q?t=363

**Comment by dj-pundir** [comment]
Hey @jzaki , @voltrevo  I would like to contribute to this project. Could you please assign this issue to me. Thanks in advance!!

**Comment by voltrevo** [comment]
@dpundir-vertex Awesome. Assigned 🙌.
