### ISSUE TITLE
Make button loading state pretty

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#231]
Currently when you press a button like 'Add Wallet' it shows a loading state for a few moments, but this loading state is just a dark background. Instead it should be a loading spinner or some other appropriate nice animation.

**Comment by realsigridjin** [comment]
@realsnoopso go for it

**Comment by voltrevo** [comment]
@realsnoopso We're just tying the loading state to the promise (if any) of the `onPress` handler as you can see here:

https://github.com/web3well/bls-wallet/blob/main/extension/source/components/Button.tsx#L23-L36

This should be just a style change associated with the existing `btn-loading` class that is already being added and removed, but let us know if you have any queries :).

**Comment by realsigridjin** [comment]
@realsnoopso
