### ISSUE TITLE
Update BLS_DOMAIN to EIP-712

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#25]
Similarly to https://github.com/thehubbleproject/hubble-contracts/issues/587 , it would make sense to update the BLS signing domain at `VerificationGateway.BLS_DOMAIN` to match the EIP-712 domain spec.

**Comment by JohnGuilding** [comment]
Closed by #588 

As mentioned in the discussion of the PR, we took inspiration from the 712 spec, but did not match it completely as we don't need to. See PR for further context.
