### ISSUE TITLE
Track BLS Wallet usage on L2 networks

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#288]
#### Problem

We currently have poor visibility into usage of the BLS Wallet contracts that are deployed on the Arbitrum Testnet (on ~Rinkeby~ Goerli) and other future L2 networks to determine if we are seeing usage and providing value to dApps/wallets.

#### Solution

- Create an analytics dashboard which displays metrics around the usage of BLS Wallet form on chain data. [Dune Analytics](https://dune.com) is recommended but other options can also be evaluated.
- Display the following metrics across all mainnet/testnet L2s that BLS Wallet is deployed on:
  - Number of wallets
  - Number of operations submitted
  - Min, max, and avg operation gas cost
  - Gas saved from bundling transactions
  - Any other good metrics you can think of
- Link the dashboard into the root level README to makie it easily discoverable by others.
- (Optional) Find a way to embed the gas saved metric into the README.

**Comment by outsider-analytics** [comment]
@jacque006 @jzaki  Hey guys, great presentation on BLS Wallet on the 11th! Jacob, we talked about this issue yesterday for a bit (Brian Wilkes, Data Scientist & EF PSE grantee). I am going to give it a crack, but wanted to confirm:
1. @jacque006  This is what we were discussing
2. I read a bunch of the documentation this morning, and it's really good! However, I am struggling to know where to look on chain for the contracts.  My apologies if I am missing it, but what are your deployed contract addresses?  (if I'm not missing it this would be a good addition to the docs :slightly_smiling_face:)

**Comment by jacque006** [comment]
@outsider-analytics Yep, this is the issue. You can find current deployments at https://github.com/web3well/bls-wallet/tree/main/contracts/networks . I would only use the Goerli one . I've made a note to update our documentation to make those more discoverable in the future.

**Comment by outsider-analytics** [comment]
@jacque006 I have bad news. Unfortunately, dune does not provide access to testnet data.  I checked around my network and I can't find an easy solution to get access to that data.  The three solutions I can think of would be:
1. Goerli Arbiscan's API calls: it would be a bigger job and I can't 100% promise success with that (as I haven't used them)
2. Running Cloud based Archive nodes for both Goerli and the Goerli Arbitrum transactions. This would be a pretty cool project, but It would not be free or quick.
3. Do a more manual static analysis using Goerli Arbiscan & Etherscan without the APIs.  This would undoubtedly be the easiest, but would not continue dynamically.
Without Bigquery or Dune this would be a significant project for me, as I would need to first get the data. If it's important to the project I'm confident I can make it happen.  Let me know what y'all's thoughts are and what direction makes the most sense!

**Comment by jacque006** [comment]
@outsider-analytics Thanks for the thorough options, we're going to discuss next week during our team sync.

**Comment by kautukkundan** [comment]
Another alternative would be using the graph protocol to generate a subgraph and then consuming it's API to build dashboards ourselves.

docs - https://thegraph.com/docs/en/cookbook/quick-start/

pros: 
- can track on-chain data with flexibility 
- works with testnets

cons:
- lot of manpower required to build subgraph and then dashboard from scratch
- only indexes events

**Comment by outsider-analytics** [comment]
Oh great thought @kautukkundan, that would be a really good option!

**Comment by outsider-analytics** [comment]
@jacque006 @kautukkundan Dune just went live with test net data 🔥 Want me to give this project a run? Just was made a bronze winner for the EF merge data competition so I'm feeling dangerous 😂

**Comment by jzaki** [comment]
Could eventually display data in a dashboard-like format. Eg... 
![image](https://user-images.githubusercontent.com/939603/210547781-6849fa5b-1cf6-4b26-a9c6-543084d0227f.png)

**Comment by jacque006** [comment]
Completed by @outsider-analytics & @Ian-Bright . Thanks!

Dashboard: https://wax-v1-analytics.vercel.app/
Frontend: https://github.com/Ian-Bright/bls-frontend ([mirror](https://github.com/getwax/bls-frontend))
Server: https://github.com/Ian-Bright/bls-server ([mirror](https://github.com/getwax/bls-server))

Pending post: https://hackmd.io/EV2_-A67Qa2j5Ol0NUmdBw?view
Contract notes: https://docs.google.com/document/d/1HiURWgM15l6NBTwcWKnt5tPTY0gZB56PT7XdcNwZQYM
