### ISSUE TITLE
Gasless dApp Example

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#300]
As a dApp developer, I would like an example of a dApp which pays for the dApp user's gas so I can augment my dApp to more easily onboard new users.

### Considerations
- Wrap an existing, well known dApp contract in a gas paying/subsidizing contract(s)?
- Should this example be in another repo?
- Use a simple allow list or another gating criteria to restrict who can be paid for.
- Limit the aggregator addresses that can be subsidized.

**Comment by jacque006** [comment]
After discussion with @kautukkundan & @jzaki , we think there are two primary ways of doing this at the moment:

### dApp Aggregator

The dApp frontend uses its own aggregator (or aggregator-proxy) instead submitting to an RPC node. This aggregation instance then has internal logic which qualifies which bundles it will pay for and which ones it will not.

This is what I believe @JohnGuilding is currently looking into.

### Wrapper Contract

A contract is written around an existing dApp which subsidizes/pays for calls by paying `tx.origin` if a user meets criteria in the contract.

1. User calls wrapper contract in an action, including in args the gas rate to use, via a BLS Wallet bundle through the VerificationGateway
2. Wrapper contract qualifies whether it will pay for the tx. This could be by address, held NFT, number of times called before, etc.
3. Wrapper contract calls original dApp contract using delegatecall
4. Use `gasleft()` around these calls to calculate the costs.
5. Wrapper contract pays `tx.origin` calculated cost (plus some padding for subsequent ops)  times gas rate

### Tradeoffs & Issues

dApps running their own aggregator is simpler with current code we have, but adds a point of centralization and requires dApps to host their own aggregators. The Quill extension also does not currently support custom aggregator urls, so it/other wallets would need a way to get those aggregator urls from dApps.

The wrapper contract should also work with existing aggregator/contract code, but caries the standard smart contract security risks. There is also some uncertainty that we can properly proxy the wallet's call through to the original dApp contract. However, it would allow any aggregator to run the Bundle/root tx, and could eventually allow MEV bots & L2 nodes to be bundle submitters with a profit motive.

**Comment by voltrevo** [comment]
If you use a wrapper contract, make sure you also include the gas associated with the calldata, since this won't be included in the `gasleft()` difference.

The 'Paying for Calldata' section I wrote up for our 4337 stuff has some more detail on this:
https://hackmd.io/6_rTYV--SimB3lTlLVFOmg#Paying-for-Calldata
