### ISSUE TITLE
Add better failure messaging for bundles

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#301]
As an aggregator operator (and maybe consumer), I would like to know why a bundle has not been submitted so I can more easily troubleshoot issues with my aggregator configuration or bundles I submit.

### Possible solution(s)
- Log out when a bundle fails to be included in the next submission and why it was not included.
- Return an error/failure status and the reason for the error/failure when querying `/bundleReceipt/:hash`.

**Comment by kautukkundan** [comment]
follow up for #193
