### ISSUE TITLE
Scaffold-ETH Integration

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#306]
Integrate the BLS client module into scaffold-eth
- [x] Send transactions using the bls client module locally
- [x] Show balances correctly
- [x] Remove redundant networks from the app
- [x] Add support for arbitrum testnet
- [x] Dapp integration showcasing BLS Wallet features

**Comment by kautukkundan** [comment]
Discuss addition of Web3Provider vs Custom BLSwallet provider
@jacque006 @JohnGuilding @kautukkundan

**Comment by kautukkundan** [comment]
creation of separate module moved to #312 

using basic integration similar to instant wallet

**Comment by jacque006** [comment]
Blocked by https://github.com/web3well/bls-wallet/issues/347

**Comment by JohnGuilding** [comment]
Single Pool Dex example - https://github.com/JohnGuilding/single-pool-dex
Punk Wallet example - https://github.com/JohnGuilding/punk-wallet
