### ISSUE TITLE
Set recovery hash from browser wallet

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#309]
Expanding from #290 
Recovery functionality described [here](https://hackmd.io/dQThDe5RT_OBS-n5s2HM_Q#Wallet-recovery).
Smart contract tests of recovery [here](https://github.com/web3well/bls-wallet/blob/main/contracts/test/recovery-test.ts).
In lieu of the `fixture` file used in the tests, the client module might have some helper functions (or could have some written). @kautukkundan can help here.

The UX could be text fields for the address and salt, then a button to:
- construct the hash
- create the transaction for the wallet to call its `setRecoveryHash` function

Once processed (first time) the `[recoveryHash](https://github.com/web3well/bls-wallet/blob/main/contracts/contracts/BLSWallet.sol#L17)` can be displayed.
FYI Subsequent setting of the recovery hash has a security delay, alongside other important functions like setting the trusted gateway.

**Comment by jacque006** [comment]
Related: https://github.com/web3well/bls-wallet/issues/220 . Assume we should close that (#220) and split it up into pieces?

**Comment by blakecduncan** [comment]
Now that this is in review I wanted to add some more details on the implementation.

The work done in this ticket:
- Add a "Review" button in the header
- The review button opens a modal where the user can enter a recovery address and a salt
- The instant wallet makes a call to the setRecoveryHash method
- The instant notifies the user of a successful transaction.

Find a loom of the UX here https://www.loom.com/share/76bf51add850403fae02db4b1e3805ad
