### ISSUE TITLE
Remove nickname step from onboarding

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#317]
I think we're going to de-scope this feature (nicknames) anyway.

Even if we don't, do you really need a nickname? Especially when there's only one wallet?

**Comment by kautukkundan** [comment]
I think we should let nicknames be in the system and actually use it later in future. The nick-name we set initially would be used for the first wallet.

I see this feature useful when we implement recovery/when a user recreates a wallet using saved seed phrase. They will input the name and set it for the recovered wallet for better identification. This is better than showing Wallet 1, Wallet 2 and it'll help identify which is an HD wallet and which is a recovered one.
