### ISSUE TITLE
Wallet lock+unlock feature

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#321]
Make this button work:

![Image](https://user-images.githubusercontent.com/9291586/188367286-9d65c536-d37a-4a24-a1f4-65204a4080b0.png)

(Requires completion of our encryption functionality, as well as UI for unlocking, both when opening the extension and when dApps initiate things. Might need to expand on this before starting work.)

**Comment by kautukkundan** [comment]
back-referencing #320
