### ISSUE TITLE
Fix placeholder (use real value) for tx hash in transactions table

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#329]
![Image](https://user-images.githubusercontent.com/9291586/188549557-b5fba5aa-1d45-4d7a-8599-c10a6a3e8520.png)

Fixing this should also fix the link so that the block explorer shows something relevant (probably the aggregate tx that the action was included in).

**Comment by jacque006** [comment]
This should already be stored in the `BundleService` on the aggregator https://github.com/web3well/bls-wallet/blob/main/aggregator/src/app/BundleService.ts#L44

And can be added in to the returned data here: https://github.com/web3well/bls-wallet/blob/main/aggregator/src/app/BundleService.ts#L206-L211
