### ISSUE TITLE
Create create2Deployer on Arbitrum Goerli

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#331]
- Requires special account `0xc10b4f6ec23545f22617e41f54a1de055e3bfb30`
- Must result in create2Deployer at `0xc1326d37b446bc7df7b36348c963bfcc8ef98ce3`

**Comment by kautukkundan** [comment]
https://github.com/safe-global/safe-singleton-factory/issues/64

**Comment by jzaki** [comment]
Related: [EIP-2470: Singleton Factory](https://eips.ethereum.org/EIPS/eip-2470)

**Comment by jzaki** [comment]
Hopefully bumped from within SAFE.
Done when this link doesn't 404 -> https://github.com/safe-global/safe-singleton-factory/tree/main/artifacts/421613

**Comment by voltrevo** [comment]
I submitted their signed transaction on Arbitrum Goerli 🤠
https://goerli.arbiscan.io/address/0x914d7fec6aac8cd542e72bca78b30650d45643d7

**Comment by voltrevo** [comment]
As a demonstration, I have deployed the `FreeMoney` contract from my recent experimentation to both Arbitrum One and Arbitrum Goerli with the same address:
https://arbiscan.io/address/0xccfee3f82a5a2b15a7ca896e7fb19a76d00f5192
https://goerli.arbiscan.io/address/0xccfee3f82a5a2b15a7ca896e7fb19a76d00f5192

I was also able to deploy the same address to my local node:
https://github.com/voltrevo/arb1-exp-nov-2022/blob/a929341/scripts/deploySafeSingletonFactory.ts
https://github.com/voltrevo/arb1-exp-nov-2022/blob/a929341/scripts/create2FreeMoney.ts

**Comment by jacque006** [comment]
Can close when https://github.com/safe-global/safe-singleton-factory/pull/80 is merged

**Comment by voltrevo** [comment]
@jzaki @jacque006 Is there any reason to wait for their PR to merge? It's already deployed to the network so I don't see how the PR affects us.

**Comment by kautukkundan** [comment]
The original PR was merged as well so we can go ahead with this too 👍🏼

**Comment by jacque006** [comment]
Confirmed artifact is present at https://github.com/safe-global/safe-singleton-factory/tree/main/artifacts/421613, closing.

Is there a follow up issue where we switch in our code/deployment scripts to the new deployer(s)?

**Comment by jacque006** [comment]
Follow up: https://github.com/web3well/bls-wallet/issues/394
