### ISSUE TITLE
Bug: ProxyAdmin's separate creation prevents consistent create2 addresses

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#332]
Currently we make the ProxyAdmin, then pass its address to VerificationGateway (via create2Deployer), then transfer ownership to the VerificationGateway:
https://github.com/web3well/bls-wallet/blob/0ef2799/contracts/shared/helpers/Fixture.ts#L73-L84

This means the ProxyAdmin address is tied to the EOA account being used, and therefore the VerificationGateway address is also tied to that EOA account. In order to get the same address on multiple networks, it is therefore required to use the same EOA account and also ensure the ProxyAdmin is created with the same nonce on that EOA account. This defeats the whole point of using create2 for us, because, while consistent addresses are possible, operating under these constraints would generate the same addresses even without create2.

ProxyAdmin is [Ownable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/3dac7bb/contracts/access/Ownable.sol), and it needs to be owned by the VerificationGateway. This also means that if we want to deploy multiple VerificationGateways (as updates are made), we also need to deploy multiple ProxyAdmins, which is a headache because ProxyAdmin needs to have a fixed address.

I think the best solution here is for VerificationGateway to deploy the ProxyAdmin. That way it'll inherit its fixed address from the VerificationGateway's fixed address (and fixed creation on startup), and will be owned by the VerificationGateway on creation rather than needing a transfer.

Maybe the reason it's not already like this is due to gas issues? If so, and if that's still a problem, I think we can still solve this but it'll be a bit more complicated.

**Comment by jzaki** [comment]
Good catch. Indeed the VerificationGateway is just under the gas limit, and I look forward consolidating requirements to date into v2, and conform to 4337. In the meantime not having the ProxyAdmin bytecode inside VG made way for other changes.
To fix this deployment issue, a small function can be added to the VG that deploys PA bytecode passed in as a parameter. (create #334 )
