### ISSUE TITLE
Nonce function not returning the correct nonce

### ISSUE THREAD

**Issue by blakecduncan** [jzaki/bls-wallet#345]
@HarryKingdon notice an issue when calling the Nonce() function.  It is always returning nonce of zero even after user actions have been submitted.

Example code with issue
```javascript
const wallet = await BlsWalletWrapper.connect(
   privateKey,
   verificationGateway,
   provider,
);
const nonce = await wallet.Nonce(); // Always returns a nonce of zero
```

There is a workaround though.  The Nonce function in BlsWalletWrapper is returning the correct nonce.

Example workaround 
```javascript
const wallet = await BlsWalletWrapper.connect(
   privateKey,
   verificationGateway,
   provider,
);
const nonce = await BlsWalletWrapper.Nonce( // Returns the correct nonce
   wallet.PublicKey(),
   verificationGateway,
   provider,
)
```

**Comment by voltrevo** [comment]
This can happen when the contracts are not in sync with bls-wallet-clients. Do we know what aggregator and what version of bls-wallet-clients was being used?

**Comment by baz-lightyear** [comment]
I can confirm that the error occured when I was not the latest version of bls-wallet-clients but rather the latest patch release - thanks Andrew
