### ISSUE TITLE
Transfer related repos to web3well

### ISSUE THREAD

**Issue by kautukkundan** [jzaki/bls-wallet#359]

**Comment by kautukkundan** [comment]
- [x] @kautukkundan - multi-action ERC20 demo
- [x] @blakecduncan - instant wallet
- [x] @JohnGuilding - scaffold-eth example
- [x] @voltrevo - gasless dapp example

**Comment by kautukkundan** [comment]
moved - https://github.com/web3well/BLSWallet-ERC20-demo

next steps is to include the relevant contracts in the same repo, right now they are in a separate repo

**Comment by blakecduncan** [comment]
Moved the instant wallet - https://github.com/web3well/bls-browser-wallet

**Comment by JohnGuilding** [comment]
Moved the single-pool-dex - https://github.com/web3well/bls-single-pool-dex

**Comment by blakecduncan** [comment]
Hey @voltrevo just wanted to give you a heads-up because we created this ticket while you were off.  We decided to move all our example apps to the web3well repo and we are using this ticket to track it.  We included your dapp example as one of the repos that could be moved

**Comment by jacque006** [comment]
https://github.com/web3well/bls-wallet-billboard
