### ISSUE TITLE
Debug BLS transactions

### ISSUE THREAD

**Issue by JohnGuilding** [jzaki/bls-wallet#362]
**As a** developer,
**I want** a tool that helps me debug BLS transactions
**So that** I can inspect and view information about individual transactions

One area of friction when working with BLS transactions is having the ability to debug individual transactions that have been bundled together. We should create a tool for developers to easily debug and inspect information about BLS transactions.

One idea that was floated some time ago was building a dedicated block explorer. This would be a considerable amount of work so this issue does not encompass building a block explorer. The scope of this issue is to build a basic tool that a developer can use to inspect BLS transactions.

**Comment by jacque006** [comment]
@JohnGuilding Does https://github.com/web3well/bls-wallet/pull/350/commits/637900613316382395918303a459843e27637ac9 from https://github.com/web3well/bls-wallet/pull/350 address this need? Or do we need more than that?

**Comment by JohnGuilding** [comment]
@jacque006 that does look like it achieves a similar goal. @jzaki would you be happy with the `getOperationResults` function added to `bls-wallet-clients` in [6379006](https://github.com/web3well/bls-wallet/commit/637900613316382395918303a459843e27637ac9). Or do we think a dedicated tool would be more appropriate?

**Comment by jacque006** [comment]
Per discussion with team, also need to decode results from each action into a dev-usable format and not just bytes. Should know return type and abi decode know on function return types.

**Comment by jacque006** [comment]
Convert to milestone, include txn hash/parsing issues

**Comment by jacque006** [comment]
Closing in favor of https://github.com/web3well/bls-wallet/milestone/5
