### ISSUE TITLE
Add multi-action transactions to BlsProvider & BlsSigner

### ISSUE THREAD

**Issue by JohnGuilding** [jzaki/bls-wallet#375]
As part of the work to create a BlsProvider and BlsSigner, we should create a way for a user to send multi-action transactions. This work should be undertaken after we have added functionality to send BLS transactions using the BlsProvider and BlsSigner.

There are methods to send transactions using the provider and signer, so both classes will require changes.

Note: not including sending regular BLS transactions, the remaining major BLS Wallet features such as recovery and gasless transactions are deemed out of scope for the Bls provider/signer MVP.

**Comment by jacque006** [comment]
For the multi-txn RPC spec, check with https://allwallet.dev/ and/or https://github.com/ChainAgnostic/CASA to see if there is good draft/standard already in place

**Comment by JohnGuilding** [comment]
Some interfaces:
- wallet_batchTransactions JSON-RPC method (v1, EOA-compatible). Provides EOA and SCW compatible interface. Was posted in Ethereum Wallets discord a while back and hasn't seen activity in a while: [wallet_batchTransactions](https://gist.github.com/mikhailxyz/773ba5196b5a7046423592204e5bc5c4)
- EIP-5792: Wallet Function Call API - Adds JSON-RPC methods for sending multiple function calls from the user's wallet, and checking their status. Adopted by candide and eth magicians thread was active 18 days ago. Still in draft: [EIP-5792](https://eips.ethereum.org/EIPS/eip-5792)
- Seems to be for sending bundles of transactions to MEV block builders, but might be useful for future ideation: [eth_sendBundle](https://docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint)
