### ISSUE TITLE
BlsSigner JsonRpcSigner & Signer Methods

### ISSUE THREAD

**Issue by JohnGuilding** [jzaki/bls-wallet#383]
We are adding a BlsSigner to `bls-wallet-clients`. This issue is concerned with ensuring the JsonRpcSigner & Signer Methods work with the BlsSigner. This will include overriding methods with BLS logic if needed and testing the other methods work as expected.

Some of the operations include connecting to an [unchecked signer](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/#UncheckedJsonRpcSigner), getting the account address and checking if an object is a signer.

**Note 1**: The term Signer Methods here does not mean every method on the ethers `Signer` class. This refers to the [following section](https://docs.ethers.io/v5/api/signer/#Signer) in their docs that group these methods under no specific heading. Other `Signer` methods are included in other issues.

**Note 2**: There is one method called `getUncheckedSigner()` that returns a `JsonRpcUncheckedSigner`. If we were to implement this method, we would have to ensure the new `BlsJsonRpcUncheckedSigner` works as expected. If this is easy to implement, we should do it as part of this issue. If not, we should raise a separate issue to address this. Using an unchecked signer is also quite a niche requirement so we may also want to decide whether it is worth implementing and testing a `BlsJsonRpcUncheckedSigner`.

[JsonRpcSigner Methods](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/#JsonRpcSigner) to test/override:

```ts
// The provider this signer was established from.
signer.provider ⇒ JsonRpcProvider

// Returns a new Signer object which does not perform additional checks when sending 
// a transaction. See getUncheckedSigner for more details.
signer.connectUnchecked( ) ⇒ JsonRpcUncheckedSignersource

// Sends the transaction and returns a Promise which resolves to the opaque transaction hash.
signer.sendUncheckedTransaction( transaction ) ⇒ Promise< string< DataHexString< 32 > > >source

// Request the node unlock the account (if locked) using password.
signer.unlock( password ) ⇒ Promise< boolean >source
```

[Signer Methods](https://docs.ethers.io/v5/api/signer/#Signer) to test/override:
```ts
// Sub-classes must implement this, however they may simply throw an error if 
// changing providers is not supported.
signer.connect( provider ) ⇒ Signer

// Returns a Promise that resolves to the account address.
signer.getAddress( ) ⇒ Promise< string< Address > >

// Returns true if and only if object is a Signer.
Signer.isSigner( object ) ⇒ boolean
```

**Comment by jacque006** [comment]
Completed in https://github.com/web3well/bls-wallet/pull/439
