### ISSUE TITLE
Better DApp integration

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#41]
Ensure extension can work with...
- [x] OpenSea
- [x] UniSwap
- [ ] OETH - sign in with Ethereum
- [x] Token transfers (L1-L2 bridge?)
- [x] Game

**Comment by kautukkundan** [comment]
https://slow-dracorex-303.notion.site/a915b91463c24cdbac72f90ffce9f264?v=b22523f2b1eb4c2ca8b8771fc9cfe1eb
compiled a list here, will keep adding more apps
