### ISSUE TITLE
Add health endpoint to aggregator

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#411]
**As an** aggregator operator,
**I would like** to know if an aggregator instance is running,
**So I can** take action when it goes down/offline/crashes

### Recommendation
- Add a `/health` endpoint to the aggregator that just responds with `HTTP 200`. If the request times out then the agg is down.

### Considerations
- As part of the health endpoint being called, we may also want to run 'pings' against our postgres & rpc connections to make sure they are alive as well.

**Comment by voltrevo** [comment]
> just responds with HTTP 200

Also worth responding with `{}` in the body. This way clients can parse the response body as json without worrying about the empty special case. (It's common to respond to `/health` with some useful data.)

**Comment by nooma-42** [comment]
I sent a draft PR to this issue, do I have to add a test for healthendpoint?

**Comment by jacque006** [comment]
@NOOMA-42 Yes, please add a simple test to make sure the endpoint responds as expected. See existing aggregator tests for examples.

**Comment by nooma-42** [comment]
I've just added a test
