### ISSUE TITLE
Update values returned in bundle receipt to more closely match ethers transaction response

### ISSUE THREAD

**Issue by JohnGuilding** [jzaki/bls-wallet#412]
We should update the bundle receipt to return additional information about the transaction. This means updating the `lookupReceipt()` method in the `BundleService`.

The bundle receipt currently looks like this:

```ts
export type BundleReceipt = {
  transactionIndex: string;
  transactionHash: string;
  bundleHash: string;
  blockHash: string;
  blockNumber: string;
};
```

As part of the provider work, we need to return an ethers transaction receipt that looks like this:

```ts
export interface TransactionReceipt {
  to: string;
  from: string;
  contractAddress: string,
  transactionIndex: number,
  root?: string,
  gasUsed: BigNumber,
  logsBloom: string,
  blockHash: string,
  transactionHash: string,
  logs: Array<Log>,
  blockNumber: number,
  confirmations: number,
  cumulativeGasUsed: BigNumber,
  effectiveGasPrice: BigNumber,
  byzantium: boolean,
  type: number;
  status?: number
};
```

The transaction receipt information is mostly derived from the bundle receipt, but there a several pieces of information missing. We can improve this by updating the `lookupReceipt()` method in the `BundleService`. 

As part of the BLS provider/signer work, we have overridden the ethers getTransactionReceipt() method which calls `_getTransactionReceipt()`. A developer would use this either by explicitly calling `provider.getTransactionReceipt()`, or more commonly, by calling it implicitly with `await tx.wait()` after sending a transaction.

We should update `_getTransactionReceipt()` so that it returns a more accurate transaction receipt in the `BlsProvider`.

Note: There are a few other TODOs that are related to this issue that should be completed as part of this work. In `bls-wallet`, search for "// TODO: bls-wallet #412" to find them

**Comment by JohnGuilding** [comment]
Duplicate of #435

**Comment by jacque006** [comment]
@JohnGuilding Can you link the original (non-dupe) issue here?
