### ISSUE TITLE
Move references to private key outside of BlsSigner

### ISSUE THREAD

**Issue by JohnGuilding** [jzaki/bls-wallet#413]
## Summary

Currently, the BlsSigner is based off of `JsonRpcSigner` and has a singleton BlsWalletWrapped instance attached. This means the class 'knows' it's own private key. 

In ethers, there are two main types of signer:

- [Wallet](https://docs.ethers.io/v5/api/signer/#Wallet), which is a class which knows its private key and can execute any operations with it.
- [JsonRpcSigner](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/#JsonRpcSigner), which is connected to a [JsonRpcProvider](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/) (or sub-class) and is acquired using [getSigner](https://docs.ethers.io/v5/api/providers/jsonrpc-provider/#JsonRpcProvider-getSigner)

If you do a ctrl f for "privateKey", you can find it implemented in the ethers `Wallet` class, but no reference in the `JsonRpcSigner`. This combined with the above information from the docs suggests that if a signer class knows it own private key, it is more similar to a Wallet class and may not accurately represent a JsonRpcSigner class.

## Tasks
- Move reference of private key from BlsSigner?
- Keep private key but re-model class based on `Wallet`?
- Do both of the above tasks and have two bls signers - something like `BlsWallet.ts` and `BlsJsonRpcSigner`?

### Further reading 1
"The Wallet singer is used when your ethers.js instance knows the private key directly."

"Since MetaMask doesn't share the key with other applications, ethers.js uses the JsonRpcSigner to be able to request the local MetaMask instance over its API to sign the transaction when needed, and then receive the signed transaction back, without ethers.js ever knowing the key."

Taken from [What is the difference between a Wallet and a JsonRpcSigner?](https://stackoverflow.com/questions/71755563/what-is-the-difference-between-a-wallet-and-a-jsonrpcsigner)

### Further reading 2
"Backends like [Metamask](https://docs.metamask.io/guide/signing-data.html#a-brief-history), [Geth](https://geth.ethereum.org/docs/rpc/ns-personal), [Parity](https://openethereum.github.io/JSONRPC-personal-module) (and many more) have an RPC interface that allows an external application to interact with them using eth_signTransaction or personal_signTransaction RPC methods, while not giving access to private keys to the application. The application has to prepare an unsigned transaction object and send it to the provider. And in response, the provider returns back the signature, which the application can then broadcast to the network (some providers can also broadcast the transaction)."

"The provider.getSigner(address) in ethers.js, takes in an address and creates a JsonRpcSigner instance, which uses the appropriate methods in from field when submitting a transaction. If you just pass in any random eth address whose private key is not with the provider, the provider will attempt if it has in its accounts, else it will just give you some error."

Taken from [Can jsonRpcProvider.getSigner() take any address as an argument?](https://ethereum.stackexchange.com/questions/98690/can-jsonrpcprovider-getsigner-take-any-address-as-an-argument)

**Comment by jacque006** [comment]
Completed in https://github.com/web3well/bls-wallet/pull/548
