### ISSUE TITLE
Uncaught aggregator error when submitting a bundle with invalid contract address

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#421]
### Steps to Reproduce

Construct a bundle where one of the actions has a `contractAddress` of `0x`.

```typescript
const bundle = wallet.sign({
    nonce: await wallet.Nonce(),
    actions: [{
      ethValue: ethers.utils.parseEther("1"),
      contractAddress: "0x",
      encodedFunction: "0x",
    }],
  });
```

Then submit the bundle to an aggregator

### Expected Result

- Aggregator rejects the bundle for being invalid (HTTP 400) or
- Aggregator fails bundle and does not include it

### Actual result

Aggregator crashes due to uncaught exception. This persists between restarts

![image](https://user-images.githubusercontent.com/10394161/206605167-3b07f9d3-8572-4f3c-9162-6744f24bdc20.png)

### Severity

A malicious or unknowing user could DoS an aggregator instance(s)

**Comment by thearyanag** [comment]
Hey @jacque006 can you assign this to me ?

**Comment by jacque006** [comment]
@thearyanag done, let us know if you have any questions or need help working on this. Thanks for picking it up!

**Comment by thearyanag** [comment]
> @thearyanag done, let us know if you have any questions or need help working on this. Thanks for picking it up!

Sure, thanks for the support!

**Comment by thearyanag** [comment]
@jacque006 hey , can you please specify exactly how can I reproduce it. I tried but not clear.


is there any other way to connect to bls-wallet team ? slack or so ?

**Comment by jacque006** [comment]
@thearyanag we have a discord server for web3well at https://discord.gg/hGDmAhcRyz , easiest way to get in touch. Can ping me there or in a DM `@jacque006#2825`

**Comment by jacque006** [comment]
High level overview: https://github.com/web3well/bls-wallet/blob/main/docs/system_overview.md
Local repo/project setup instructions: https://github.com/web3well/bls-wallet/blob/main/docs/local_development.md
Example of how to send a transaction: https://github.com/web3well/bls-wallet/blob/main/docs/use_bls_wallet_clients.md#send-a-transaction

Main thing to reproduce is setting `contractAddress: "0x"` in an action and submitting to an aggregator. The fix will likely be in aggregator code or in client.

**Comment by jacque006** [comment]
@thearyanag Did you still want to work on this? We are spinning down active work on this project. If not, I will close.
