### ISSUE TITLE
Gas under-estimated for recovery via blswallet

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#426]
Recovering a blswallet via another blswallet fails runs out of gas. The gasLimit is set by the aggregator via a call to ethers' `estimateGas` function, and this seems to be just not enough to get through the call to recoverWallet in VerificationGateway.

Update the ethers module where used, and potentially other modules in the contracts folder.

**Comment by voltrevo** [comment]
Sounds like the same issue I ran into during #464:

> There's also a workaround called fx.processBundleWithExtraGas. The automatic gasLimit isn't sufficient for setPendingBLSKeyForWallet, I think this has to do with the call depth involved... ie, the gasLimit is enough for the actual amount of gas used, but not enough gas is provided to one of the deeply nested calls since 63/64ths of the gas is provided to each next layer.

Maybe those changes would resolve this issue?
