### ISSUE TITLE
Deploy contracts & run aggregator for Optimism Goerli

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#441]
*As a* web3 developers
*I would like to* have a BLS Wallet contract & aggregator deployment on Optimism Goerli
*So I can* integrate or test BLS Wallet on Optimism

### Notes
https://chainlist.org/chain/420

We should also remove the Arbitrum Rinkeby network config & documentation references as those contracts no longer work with latest client libs/aggregator.

**Comment by jacque006** [comment]
It also may be worth getting off the Arbitrum/Optimism Goerli public RPC endpoints as we are getting rate limited by them

**Comment by jzaki** [comment]
Are there different types of Optimism, (a la Arbitrum's Nitro vs Nova)?
Will need to look into "Bedrock" & "Cannon".
