### ISSUE TITLE
Document pain points setting up local development environment using Windows

### ISSUE THREAD

**Issue by JohnGuilding** [jzaki/bls-wallet#465]
**As a** contributor using a Windows machine,
**I want to** know what the pain points/gotchas are when setting up my dev environment,
**So that** I can more easily get setup on a windows machine

## Description

As part of #435, we realised that our local development environment setup has not been made Windows compatible. We should ensure that contributors using Windows can easily work with bls-wallet. **This issue is concerned with documenting pain points.** A follow up issue(s) will be created to implement the needed changes.

## Acceptance criteria:
- List of pain points is documented (This may include errors encountered, setup required etc.)
- In the form of either 1) A publicly available link e.g. hackmd note or notion page 2) The comment section of this issue

**Comment by ri-dev-git** [comment]
1] When I run ./setup with deno in normal windows terminal (not using wsl) it pops up with an error:
![image](https://user-images.githubusercontent.com/67939540/213622655-f44f3fa5-4a89-43ae-943a-6a7841736545.png)
2]I was able to run the setup script when i switched to WSL terminal. Following are the steps which helped me to run the setup script:

- I think while setting up local development a developer would require WSL installed on his windows system to run the `./setup` script.
- To run deno you need to install it seperately for WSL using `curl -fsSL https://deno.land/x/install/install.sh | sh` which requires an unzip package which can be installed using `sudo apt install unzip`
- i ran into an error of `could not get lock /var/lib/dpkg/lock-frontend` while setting up unzip, which i debugged by referring to an [youtube video](https://www.youtube.com/watch?v=geqfRyAl2vQ&t)
- switched to node v16.0.0 using `nvm use 16.0.0`'
- ran `deno run --allow-read ./setup.ts` command.

3]While running `yarn start` and `yarn start-hardhat` I bumped in an error of terminal not discovering the file
![image](https://user-images.githubusercontent.com/67939540/213626597-7d6008aa-68f6-408f-9246-b853b6481d66.png)

4] By using earlier versions of local development documentation I was able to :

- run hardhat node
- fund the deployer
- deploy all the scripts

I used the prior commands to perform these tasks and not the one mentioned in point 3 as it would throw an error

5]while deploying i ran into an error of:
![image](https://user-images.githubusercontent.com/67939540/213628690-4efe93d1-e399-4845-9efd-f7152956b1f0.png)
Which with prior discussions cleared that it was meant to be deleted and ran the deploy command which resulted in an error of  not able to find module:
![image](https://user-images.githubusercontent.com/67939540/213629849-d79eb332-334e-4cba-9681-52e375a828f6.png)

To resolve this I had to clone the repo again and run through step 4 again. I did not encounter errors this time

6]Docker set up requires integration with WSL. 
- It can be achieved using settings of docker.
- I personally am running into some trouble which is related to .wslconfig in user directory.
- I am trying to look deeper into it for now.

I would hit back If i am able to resolve it and would shout if I couldn't
Hope this helps!:) 
Also i couldn't assign myself to the task as i don't have write permission to the project!

**Comment by JohnGuilding** [comment]
Awesome thanks @ri-dev-git 

We're going to look into making our setup machine agnostic next week. The end result is if you can run docker successfully, things should just work. 

In the meantime, I would make sure you can use docker on your machine with no problems. Will report back when we've got things set up. We've got a few things on atm, but looking to get this sorted over the next few weeks :)

**Comment by JohnGuilding** [comment]
Follow up issue #476
