### ISSUE TITLE
BlsSigner cannot deploy contract

### ISSUE THREAD

**Issue by JohnGuilding** [jzaki/bls-wallet#466]
The BlsSigner cannot deploy a contract. 

```ts
const MockERC20 = await ethers.getContractFactory("MockERC20");
mockERC20 = await MockERC20.connect(blsSigner).deploy(
    "AnyToken",
    "TOK",
    tokenSupply,
);
```

Results in this error:
`TypeError: Transaction.to should be defined`.

Deploying a contract using a signer is a common task, so we should investigate why this is and implement a fix.

**Comment by jacque006** [comment]
@JohnGuilding This is a dupe of https://github.com/web3well/bls-wallet/issues/182 . Per comments in that issue, it doesn't not look like this was slated for V1, although it looks like @jzaki may have added it back in scope?

**Comment by JohnGuilding** [comment]
Duplicate of #182
