### ISSUE TITLE
Use environmental variables for sensitive info in example dApps

### ISSUE THREAD

**Issue by JohnGuilding** [jzaki/bls-wallet#474]
- [ ] single-pool-dex
- [ ] billboard
- [ ] ERC20 demo

**Comment by jacque006** [comment]
@JohnGuilding @blakecduncan @voltrevo Was this already completed?

**Comment by blakecduncan** [comment]
@jacque006 I think most of the examples are using env variables.  There are a few that I don't think were updated, like the billboard, the bls-single-pool-dex, the erc20-demo.  But I don't think any of those are using the private rpc endpoints so I don't think it really matters

Edit - just saw that this ticket specifically mentions those three apps.  But the point about the rpc endpoints still stands
