### ISSUE TITLE
Assess use of, and remove unnecessary manual tests

### ISSUE THREAD

**Issue by JohnGuilding** [jzaki/bls-wallet#475]
We have a number of manual tests located at `./aggregator/manualTests`. We should assess the use of these tests, as much of the logic is now tested in the integration tests. They are also used for exploratory testing, so we should assess whether some are still needed for this also.

**Comment by voltrevo** [comment]
@JohnGuilding I believe we can just close this? Or maybe we can have a quick chat to finalize?

**Comment by JohnGuilding** [comment]
@voltrevo agreed, all makes sense regarding what they're used for 👍

**Comment by JohnGuilding** [comment]
Closed as manual tests are used for exploratory testing
