### ISSUE TITLE
Handle non-sequential nonces

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#505]
Verification of sequential nonces requires just reading the next nonce from the wallet.
Wallets implementing non-sequential nonces may enable transactions to be signed with one of several valid nonces. Verifying a wallet's nonce thus requires passing the tx nonce to the wallet to verify.

**Comment by voltrevo** [comment]
In 4337, the solution to this is that the wallet implements `validateUserOp` which is where the nonce check occurs. Wallets are therefore able to implement variations on nonce logic here.

This might be something we want to leave until we move to 4337?
