### ISSUE TITLE
Implement registries for storing BLSPublicKeys and addresses on-chain

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#522]
A BLSPublicKey is 128 bytes.

Including these bytes for each operation is a showstopper for achieving cheaper transactions. They need to be stored on-chain and referenced instead.

Addresses can benefit in the same way, as 20 bytes is still a big opportunity for saving bytes (shooting for less than 20 bytes *total* for simple txs).

The index that maps to the BLSPublicKey/address should be auto-increment. Users should not be allowed to choose any unallocated index. Doing that would lead to unnecessary complexity in finding the smallest available index.

The registry should not be opinionated about how the index is encoded. Just use `uint256` - it's up to the expander to decide the encoding (see https://github.com/web3well/bls-wallet/issues/524), and different expanders are free to do this differently while benefitting from the same registry.

When a user sends us their BLSPublicKey, we need to do the inverse off-chain - map the data back to the index. This can be achieved by having the contract emit an event with an index on the data. Do a manual test for this.

These registries should allocate their indexes in perpetuity. The desire to re-purpose indexes shouldn't be a problem for a very long time, and we can switch to different registries/expanders in the future.

**Comment by jacque006** [comment]
Completed in https://github.com/web3well/bls-wallet/pull/546
