### ISSUE TITLE
Use registries in fallback expander

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#523]
Requires:
- https://github.com/web3well/bls-wallet/issues/521
- https://github.com/web3well/bls-wallet/issues/522
- https://github.com/web3well/bls-wallet/issues/524

After [pseudo-floats](https://github.com/web3well/bls-wallet/pull/519), an ETH transfer is expected to be encoded as 184 bytes using the fallback expander:

| Field               | Format      | Bytes Used |
|---------------------|-------------|------------|
| expanderIndex       | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 1          |
| BLS Public Key      | Raw         | 128        |
| Nonce               | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 2 (ish)    |
| Gas                 | [PseudoFloat](https://github.com/web3well/bls-wallet/blob/74d31d5/contracts/contracts/lib/PseudoFloat.sol#L8-L70) | 2          |
| Action Count        | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 1          |
| [0] ethValue        | [PseudoFloat](https://github.com/web3well/bls-wallet/blob/74d31d5/contracts/contracts/lib/PseudoFloat.sol#L8-L70) | 2 (ish)    |
| [0] contractAddress | Raw         | 20         |
| [0] dataLen         | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 1          |
| [0] data            | Raw         | 0          |
| [1] ethValue        | [PseudoFloat](https://github.com/web3well/bls-wallet/blob/74d31d5/contracts/contracts/lib/PseudoFloat.sol#L8-L70) | 2          |
| [1] contractAddress | Raw         | 20         |
| [1] dataLen         | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 1          |
| [1] data            | Raw         | 4          |
|                     |             |            |
| Total               |             | 184 (ish)  |

(Note that this includes an action to compensate tx.origin.)

These bytes are dominated (90%) by the BLS Public Key (70%) and addresses (20%).

Because this is the fallback expander, we cannot assume that anything is available in a registry.

Instead, we can add another VLQ to use as a bit array to determine whether each BLS key/address uses the registry or is included inline. This will consume 1 byte, unless you need more than 6 actions (7 usable bits in each byte of a VLQ).

This way, when an operation uses registries for these values, the byte usage will change to this:

| Field               | Format      | Bytes Used |
|---------------------|-------------|------------|
| expanderIndex       | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 1          |
| Registry Usage Bits | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 1          |
| BLS Public Key      | [RegIndex](https://github.com/web3well/bls-wallet/issues/524)    | 3 (ish)    |
| Nonce               | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 2 (ish)    |
| Gas                 | [PseudoFloat](https://github.com/web3well/bls-wallet/blob/74d31d5/contracts/contracts/lib/PseudoFloat.sol#L8-L70) | 2          |
| Action Count        | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 1          |
| [0] ethValue        | [PseudoFloat](https://github.com/web3well/bls-wallet/blob/74d31d5/contracts/contracts/lib/PseudoFloat.sol#L8-L70) | 2 (ish)    |
| [0] contractAddress | [RegIndex](https://github.com/web3well/bls-wallet/issues/524)    | 3 (ish)    |
| [0] dataLen         | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 1          |
| [0] data            | Raw         | 0          |
| [1] ethValue        | [PseudoFloat](https://github.com/web3well/bls-wallet/blob/74d31d5/contracts/contracts/lib/PseudoFloat.sol#L8-L70) | 2          |
| [1] contractAddress | [RegIndex](https://github.com/web3well/bls-wallet/issues/524)    | 3 (ish)    |
| [1] dataLen         | [VLQ](https://github.com/web3well/bls-wallet/blob/a4aaa42/contracts/contracts/lib/VLQ.sol#L6-L24)         | 1          |
| [1] data            | Raw         | 4          |
|                     |             |            |
| Total               |             | 26 (ish)   |

**Comment by jacque006** [comment]
Completed in https://github.com/web3well/bls-wallet/pull/553
