### ISSUE TITLE
Implement RegIndex encoding (registry index)

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#524]
We could simply use VLQ for this, but since registries are first-come first-served, it's unfair and suboptimal to allocate 1-byte and even 2-byte indexes.

Instead, let's use a VLQ followed by two fixed bytes (for a 3-byte minimum). This has the following advantages over regular VLQ:
1. We can say publicly that we are packing addresses/etc into about 3 bytes (using/claiming fewer would cause people to criticize the obvious space limitation)
2. Avoids negative perception of the registry caused by the unfair allocation of 1 and 2 byte indexes
3. Increases the number of 3-byte indexes from 2,080,768 to 8,388,608, and the number of 4-byte indexes from 266,338,304 to 1,065,353,216.

`regIndex = vlqValue << 16 + fixedByte1 << 8 + fixedByte2`

**Comment by jacque006** [comment]
Completed in https://github.com/web3well/bls-wallet/pull/547
