### ISSUE TITLE
BLSRegistration contract (including expander)

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#525]
Requires:
- https://github.com/web3well/bls-wallet/issues/522

At some point, the full 128 bytes of the user's BLS public key need to be registered.

However, before registration, users need to send those 128 bytes to identify their account. Without a dedicated expander, they would then need to provide those 128 bytes *again* to encode the act of registering their BLS public key.

We should make it standard for users to register their address as well, so that other users can send them transfers efficiently. This doesn't cost any calldata because we can simply use `msg.sender`.

Here's an expected outline of the contract:

```solidity
contract BLSRegistration is IExpander {
  BLSPublicKeyRegistry blsPublicKeyRegistry;
  AddressRegistry addressRegistry;

  constructor() {
    // set registry addresses
  }

  function expand(bytes calldata stream) {
    // extract 128 bytes from stream as senderPublicKey
    // return senderPublicKey and an operation encoding a call to register with senderPublicKey
  }
  
  function register(uint256[4] blsPublicKey) {
    blsPublicKeyRegistry.register(blsPublicKey);
    addressRegistry.register(msg.sender);
  }
}
```

**Comment by jacque006** [comment]
Completed in https://github.com/web3well/bls-wallet/pull/555
