### ISSUE TITLE
Include an optional tx.origin payment in fallback expander

### ISSUE THREAD

**Issue by voltrevo** [jzaki/bls-wallet#554]
Encoding a `tx.origin` payment directly takes 6 bytes:

- `ethValue`: 2 bytes
- `contractAddress`: 3 bytes
- `data`: 1 byte

We can reduce this to just the 2 bytes for the `ethValue` by including a flag to enable it in the bit stream.

**Comment by jacque006** [comment]
Completed in https://github.com/web3well/bls-wallet/pull/558
