### ISSUE TITLE
Verify BLS Wallet contracts

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#559]
*As a* BLS Wallet contract consumer
*I would like to* have the contracts uploaded & verified
*So I can* trust that the deployed contracts match what is in source code

### Notes

https://ethereum.org/en/developers/docs/smart-contracts/verifying/

At a bare minimum, we should have a script that is capable of doing this process. Etherscan and/or Sourcify would be good first targets
In addition, it would be good to run this automatically on contract bytecode changes after:
- Merges to `main` and/or
- Release tags

**Comment by ViharGandhi** [comment]
Can you assign this issue to me

**Comment by jacque006** [comment]
@ViharGandhi done, thanks for picking this up! Let us know if you need any help

**Comment by ViharGandhi** [comment]
Hey should i write a new hardhat config script and deploy the smart contract on test net and then verify it ??

**Comment by jacque006** [comment]
@ViharGandhi That sounds great to me :+1: If the hardhat config script is very long, might be worth breaking out to a new file.

Feel free to message me if you want more direct contact, or jump into the [web3well discord](https://discord.gg/hGDmAhcRyz)
Discord: `jacque006#2825`
Telegram: `@jacque006`

**Comment by jacque006** [comment]
@ViharGandhi Were you still interested in working on this? Otherwise I will close
