### ISSUE TITLE
Passing TransactionReceipt to getOperationResults always results in no WalletOperationProcessed events found in transaction error

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#563]
### Problem
When an ethers.js `TransactionReceipt` is passed to `getOperationResults`, it always throws an error: `no WalletOperationProcessed events found in transaction [TXN_HASH]`.

This is because `TransactionReceipt` matches the shape/type/interface of `ContractReceipt`, which `getOperationResults` expects, but never has its `events` property populated as `TransactionReceipt`s are not aware of the contract they were originally called from and thus do not have access to the contract interface/abi.

Relevant ethers.js code: https://github.com/ethers-io/ethers.js/blob/v5.7.2/packages/contracts/src.ts/index.ts#L338-L368

### Possible Solutions
1. Add an additional check on the truthyness of `txnReceipt.events` and throw an error with a message such as `no events found in transaction ${txnReceipt.transactionHash}, are you sure it is a ContractReceipt from a VerificationGateway.processBundle transaction?` (easy) and/or
2. Add an new client function such as:
```typescript
const getOperationResultsFromTransactionReceipt = (txnReceipt: TransactionReceipt, verificationGatewayContractOrAddress: VerificationGateway | string): OperationResult[] => ...`
```
Which can take a `TransactionReceipt` and `VerificationGateway` contract instance or address and returns operation results. (harder)

**Comment by jacque006** [comment]
Also see how 4337 handles their error parsing as part of this work

**Comment by deepaksing** [comment]
Hi, Can you assign this issue to me

**Comment by JohnGuilding** [comment]
Hey @deepaksing just assigned you. Let us know if you have any questions :)

**Comment by deepaksing** [comment]
sure, Thank you for assigning.

**Comment by jacque006** [comment]
Closed in https://github.com/getwax/bls-wallet/pull/597
