### ISSUE TITLE
Configure + test deployment to Sepolia testnet

### ISSUE THREAD

**Issue by jzaki** [jzaki/bls-wallet#587]
https://ethereum.org/en/developers/docs/networks/#sepolia

**Comment by ri-dev-git** [comment]
hi @jzaki! Can i work on it?

**Comment by jacque006** [comment]
Hey @ri-dev-git , were you still interested in doing this? We will be closing most/all remaining issues in this repo as we move to more [ERC-4337](https://eips.ethereum.org/EIPS/eip-4337) related work that builds on what was started here.

**Comment by ri-dev-git** [comment]
Sadly not

**Comment by jacque006** [comment]
All good, thanks for the response :+1: Closing as won't fix
