### ISSUE TITLE
UI <-> Controller Bindings

### ISSUE THREAD

**Issue by jacque006** [jzaki/bls-wallet#63]
Create and setup bindings from extension controllers to UI components. This could be done via a `redux` pattern or something simpler.

**Comment by jacque006** [comment]
@kautukkundan Can you share the simplified `redux` package you mentioned to me awhile back here?

**Comment by kautukkundan** [comment]
here - https://easy-peasy.vercel.app

**Comment by voltrevo** [comment]
This was solved in #217 / #243.

E.g. to update state you call rpc like `quill.rpc.addHDAccount` here: https://github.com/web3well/bls-wallet/blob/main/extension/source/Home/Wallet/Wallets/WalletWrapper.tsx#L28
